name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  LANG: "en_US.UTF-8"
  LC_MESSAGES: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"
  LANGUAGE: "en_US:en"
  JAVA_HOME: ${{ github.workspace }}/jdk
  MAVEN_ARGS: >-
    --file pom.xml --show-version --batch-mode --errors --lax-checksums -Dmaven.test.skip=true

jobs:
  setup:
    name: Cancel previous builds
    runs-on: ubuntu-latest
    steps:
      - name: Stop old builds
        if: github.ref != 'refs/heads/master'
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        java: [ '11', '14', '15' ]
        architecture: [ 'x64', 'x86' ]
        os: [ ubuntu-latest, windows-latest ]
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }} with ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-package: jdk
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}

      - name: Cache Maven repository
        uses: actions/cache@v3.2.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-${{ matrix.java }}-maven-${{ hashFiles('**/*pom*.xml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-maven-

      - name: Build with Maven
        timeout-minutes: 20
        if: contains(matrix.os, 'win') == false
        run: |
          cd test-app
          chmod +x ./mvnw
          ./mvnw clean package $MAVEN_ARGS
